/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AffiliateProgramRouteImport } from './routes/affiliate-program'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountPurchasesRouteImport } from './routes/account/purchases'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountWishesRouteImport } from './routes/account/wishes'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as WishIdRouteImport } from './routes/wish.$id'
import { Route as AdminSettingsSystemRouteImport } from './routes/admin/settings/system'
import { Route as AdminSettingsWebsiteRouteImport } from './routes/admin/settings/website'
import { Route as ApiAccountPurchasesRouteImport } from './routes/api/account/purchases'
import { Route as ApiAccountWishesRouteImport } from './routes/api/account/wishes'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api/admin/categories'
import { Route as ApiAdminCommentsRouteImport } from './routes/api/admin/comments'
import { Route as ApiAdminCouponsRouteImport } from './routes/api/admin/coupons'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminMediaRouteImport } from './routes/api/admin/media'
import { Route as ApiAdminPlansRouteImport } from './routes/api/admin/plans'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminTemplatesRouteImport } from './routes/api/admin/templates'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiPublicAuthMeRouteImport } from './routes/api/public/auth-me'
import { Route as ApiPublicCategoriesRouteImport } from './routes/api/public/categories'
import { Route as ApiPublicMediaRouteImport } from './routes/api/public/media'
import { Route as ApiPublicPlansRouteImport } from './routes/api/public/plans'
import { Route as ApiPublicSettingsRouteImport } from './routes/api/public/settings'
import { Route as ApiPublicTemplatesRouteImport } from './routes/api/public/templates'
import { Route as ApiPublicWishRouteImport } from './routes/api/public/wish'
import { Route as ApiWishesCoverRouteImport } from './routes/api/wishes/cover'
import { Route as ApiWishesGenerateRouteImport } from './routes/api/wishes/generate'
import { Route as ApiAdminCategoriesIdRouteImport } from './routes/api/admin/categories.$id'
import { Route as ApiAdminCommentsIdRouteImport } from './routes/api/admin/comments.$id'
import { Route as ApiAdminCouponsIdRouteImport } from './routes/api/admin/coupons.$id'
import { Route as ApiAdminMediaIdRouteImport } from './routes/api/admin/media.$id'
import { Route as ApiAdminPlansIdRouteImport } from './routes/api/admin/plans.$id'
import { Route as ApiAdminTemplatesIdRouteImport } from './routes/api/admin/templates.$id'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users.$id'
import { Route as ApiPaymentsRazorpayOrderRouteImport } from './routes/api/payments/razorpay/order'
import { Route as ApiPaymentsRazorpayVerifyRouteImport } from './routes/api/payments/razorpay/verify'
import { Route as ApiPaymentsRazorpayWebhookRouteImport } from './routes/api/payments/razorpay/webhook'
import { Route as ApiPublicCouponsValidateRouteImport } from './routes/api/public/coupons/validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateProgramRoute = AffiliateProgramRouteImport.update({
  id: '/affiliate-program',
  path: '/affiliate-program',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPurchasesRoute = AccountPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountWishesRoute = AccountWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WishIdRoute = WishIdRouteImport.update({
  id: '/wish/$id',
  path: '/wish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsSystemRoute = AdminSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsWebsiteRoute = AdminSettingsWebsiteRouteImport.update({
  id: '/settings/website',
  path: '/settings/website',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAccountPurchasesRoute = ApiAccountPurchasesRouteImport.update({
  id: '/api/account/purchases',
  path: '/api/account/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountWishesRoute = ApiAccountWishesRouteImport.update({
  id: '/api/account/wishes',
  path: '/api/account/wishes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCommentsRoute = ApiAdminCommentsRouteImport.update({
  id: '/api/admin/comments',
  path: '/api/admin/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCouponsRoute = ApiAdminCouponsRouteImport.update({
  id: '/api/admin/coupons',
  path: '/api/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaRoute = ApiAdminMediaRouteImport.update({
  id: '/api/admin/media',
  path: '/api/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlansRoute = ApiAdminPlansRouteImport.update({
  id: '/api/admin/plans',
  path: '/api/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTemplatesRoute = ApiAdminTemplatesRouteImport.update({
  id: '/api/admin/templates',
  path: '/api/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthMeRoute = ApiPublicAuthMeRouteImport.update({
  id: '/api/public/auth-me',
  path: '/api/public/auth-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCategoriesRoute = ApiPublicCategoriesRouteImport.update({
  id: '/api/public/categories',
  path: '/api/public/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaRoute = ApiPublicMediaRouteImport.update({
  id: '/api/public/media',
  path: '/api/public/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlansRoute = ApiPublicPlansRouteImport.update({
  id: '/api/public/plans',
  path: '/api/public/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSettingsRoute = ApiPublicSettingsRouteImport.update({
  id: '/api/public/settings',
  path: '/api/public/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTemplatesRoute = ApiPublicTemplatesRouteImport.update({
  id: '/api/public/templates',
  path: '/api/public/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWishRoute = ApiPublicWishRouteImport.update({
  id: '/api/public/wish',
  path: '/api/public/wish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishesCoverRoute = ApiWishesCoverRouteImport.update({
  id: '/api/wishes/cover',
  path: '/api/wishes/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishesGenerateRoute = ApiWishesGenerateRouteImport.update({
  id: '/api/wishes/generate',
  path: '/api/wishes/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesIdRoute = ApiAdminCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCategoriesRoute,
} as any)
const ApiAdminCommentsIdRoute = ApiAdminCommentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCommentsRoute,
} as any)
const ApiAdminCouponsIdRoute = ApiAdminCouponsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCouponsRoute,
} as any)
const ApiAdminMediaIdRoute = ApiAdminMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminMediaRoute,
} as any)
const ApiAdminPlansIdRoute = ApiAdminPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminPlansRoute,
} as any)
const ApiAdminTemplatesIdRoute = ApiAdminTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminTemplatesRoute,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiPaymentsRazorpayOrderRoute =
  ApiPaymentsRazorpayOrderRouteImport.update({
    id: '/api/payments/razorpay/order',
    path: '/api/payments/razorpay/order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsRazorpayVerifyRoute =
  ApiPaymentsRazorpayVerifyRouteImport.update({
    id: '/api/payments/razorpay/verify',
    path: '/api/payments/razorpay/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsRazorpayWebhookRoute =
  ApiPaymentsRazorpayWebhookRouteImport.update({
    id: '/api/payments/razorpay/webhook',
    path: '/api/payments/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCouponsValidateRoute =
  ApiPublicCouponsValidateRouteImport.update({
    id: '/api/public/coupons/validate',
    path: '/api/public/coupons/validate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help-center': typeof HelpCenterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/templates': typeof TemplatesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/login': typeof AccountLoginRoute
  '/account/purchases': typeof AccountPurchasesRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishes': typeof AccountWishesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/wish/$id': typeof WishIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/settings/website': typeof AdminSettingsWebsiteRoute
  '/api/account/purchases': typeof ApiAccountPurchasesRoute
  '/api/account/wishes': typeof ApiAccountWishesRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/comments': typeof ApiAdminCommentsRouteWithChildren
  '/api/admin/coupons': typeof ApiAdminCouponsRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/media': typeof ApiAdminMediaRouteWithChildren
  '/api/admin/plans': typeof ApiAdminPlansRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/templates': typeof ApiAdminTemplatesRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/public/auth-me': typeof ApiPublicAuthMeRoute
  '/api/public/categories': typeof ApiPublicCategoriesRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/public/plans': typeof ApiPublicPlansRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/api/public/templates': typeof ApiPublicTemplatesRoute
  '/api/public/wish': typeof ApiPublicWishRoute
  '/api/wishes/cover': typeof ApiWishesCoverRoute
  '/api/wishes/generate': typeof ApiWishesGenerateRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/comments/$id': typeof ApiAdminCommentsIdRoute
  '/api/admin/coupons/$id': typeof ApiAdminCouponsIdRoute
  '/api/admin/media/$id': typeof ApiAdminMediaIdRoute
  '/api/admin/plans/$id': typeof ApiAdminPlansIdRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/payments/razorpay/order': typeof ApiPaymentsRazorpayOrderRoute
  '/api/payments/razorpay/verify': typeof ApiPaymentsRazorpayVerifyRoute
  '/api/payments/razorpay/webhook': typeof ApiPaymentsRazorpayWebhookRoute
  '/api/public/coupons/validate': typeof ApiPublicCouponsValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help-center': typeof HelpCenterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/templates': typeof TemplatesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/login': typeof AccountLoginRoute
  '/account/purchases': typeof AccountPurchasesRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishes': typeof AccountWishesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/wish/$id': typeof WishIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/settings/website': typeof AdminSettingsWebsiteRoute
  '/api/account/purchases': typeof ApiAccountPurchasesRoute
  '/api/account/wishes': typeof ApiAccountWishesRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/comments': typeof ApiAdminCommentsRouteWithChildren
  '/api/admin/coupons': typeof ApiAdminCouponsRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/media': typeof ApiAdminMediaRouteWithChildren
  '/api/admin/plans': typeof ApiAdminPlansRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/templates': typeof ApiAdminTemplatesRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/public/auth-me': typeof ApiPublicAuthMeRoute
  '/api/public/categories': typeof ApiPublicCategoriesRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/public/plans': typeof ApiPublicPlansRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/api/public/templates': typeof ApiPublicTemplatesRoute
  '/api/public/wish': typeof ApiPublicWishRoute
  '/api/wishes/cover': typeof ApiWishesCoverRoute
  '/api/wishes/generate': typeof ApiWishesGenerateRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/comments/$id': typeof ApiAdminCommentsIdRoute
  '/api/admin/coupons/$id': typeof ApiAdminCouponsIdRoute
  '/api/admin/media/$id': typeof ApiAdminMediaIdRoute
  '/api/admin/plans/$id': typeof ApiAdminPlansIdRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/payments/razorpay/order': typeof ApiPaymentsRazorpayOrderRoute
  '/api/payments/razorpay/verify': typeof ApiPaymentsRazorpayVerifyRoute
  '/api/payments/razorpay/webhook': typeof ApiPaymentsRazorpayWebhookRoute
  '/api/public/coupons/validate': typeof ApiPublicCouponsValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help-center': typeof HelpCenterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/templates': typeof TemplatesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/login': typeof AccountLoginRoute
  '/account/purchases': typeof AccountPurchasesRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishes': typeof AccountWishesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/wish/$id': typeof WishIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/settings/website': typeof AdminSettingsWebsiteRoute
  '/api/account/purchases': typeof ApiAccountPurchasesRoute
  '/api/account/wishes': typeof ApiAccountWishesRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/comments': typeof ApiAdminCommentsRouteWithChildren
  '/api/admin/coupons': typeof ApiAdminCouponsRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/media': typeof ApiAdminMediaRouteWithChildren
  '/api/admin/plans': typeof ApiAdminPlansRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/templates': typeof ApiAdminTemplatesRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/public/auth-me': typeof ApiPublicAuthMeRoute
  '/api/public/categories': typeof ApiPublicCategoriesRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/public/plans': typeof ApiPublicPlansRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/api/public/templates': typeof ApiPublicTemplatesRoute
  '/api/public/wish': typeof ApiPublicWishRoute
  '/api/wishes/cover': typeof ApiWishesCoverRoute
  '/api/wishes/generate': typeof ApiWishesGenerateRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/comments/$id': typeof ApiAdminCommentsIdRoute
  '/api/admin/coupons/$id': typeof ApiAdminCouponsIdRoute
  '/api/admin/media/$id': typeof ApiAdminMediaIdRoute
  '/api/admin/plans/$id': typeof ApiAdminPlansIdRoute
  '/api/admin/templates/$id': typeof ApiAdminTemplatesIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/payments/razorpay/order': typeof ApiPaymentsRazorpayOrderRoute
  '/api/payments/razorpay/verify': typeof ApiPaymentsRazorpayVerifyRoute
  '/api/payments/razorpay/webhook': typeof ApiPaymentsRazorpayWebhookRoute
  '/api/public/coupons/validate': typeof ApiPublicCouponsValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/affiliate-program'
    | '/blog'
    | '/careers'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/help-center'
    | '/how-it-works'
    | '/pricing'
    | '/privacy-policy'
    | '/templates'
    | '/terms-of-service'
    | '/account/login'
    | '/account/purchases'
    | '/account/register'
    | '/account/settings'
    | '/account/wishes'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/media'
    | '/admin/plans'
    | '/admin/templates'
    | '/admin/users'
    | '/wish/$id'
    | '/account/'
    | '/admin/'
    | '/admin/settings/system'
    | '/admin/settings/website'
    | '/api/account/purchases'
    | '/api/account/wishes'
    | '/api/admin/categories'
    | '/api/admin/comments'
    | '/api/admin/coupons'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/media'
    | '/api/admin/plans'
    | '/api/admin/stats'
    | '/api/admin/templates'
    | '/api/admin/users'
    | '/api/auth/me'
    | '/api/public/auth-me'
    | '/api/public/categories'
    | '/api/public/media'
    | '/api/public/plans'
    | '/api/public/settings'
    | '/api/public/templates'
    | '/api/public/wish'
    | '/api/wishes/cover'
    | '/api/wishes/generate'
    | '/api/admin/categories/$id'
    | '/api/admin/comments/$id'
    | '/api/admin/coupons/$id'
    | '/api/admin/media/$id'
    | '/api/admin/plans/$id'
    | '/api/admin/templates/$id'
    | '/api/admin/users/$id'
    | '/api/payments/razorpay/order'
    | '/api/payments/razorpay/verify'
    | '/api/payments/razorpay/webhook'
    | '/api/public/coupons/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-program'
    | '/blog'
    | '/careers'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/help-center'
    | '/how-it-works'
    | '/pricing'
    | '/privacy-policy'
    | '/templates'
    | '/terms-of-service'
    | '/account/login'
    | '/account/purchases'
    | '/account/register'
    | '/account/settings'
    | '/account/wishes'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/media'
    | '/admin/plans'
    | '/admin/templates'
    | '/admin/users'
    | '/wish/$id'
    | '/account'
    | '/admin'
    | '/admin/settings/system'
    | '/admin/settings/website'
    | '/api/account/purchases'
    | '/api/account/wishes'
    | '/api/admin/categories'
    | '/api/admin/comments'
    | '/api/admin/coupons'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/media'
    | '/api/admin/plans'
    | '/api/admin/stats'
    | '/api/admin/templates'
    | '/api/admin/users'
    | '/api/auth/me'
    | '/api/public/auth-me'
    | '/api/public/categories'
    | '/api/public/media'
    | '/api/public/plans'
    | '/api/public/settings'
    | '/api/public/templates'
    | '/api/public/wish'
    | '/api/wishes/cover'
    | '/api/wishes/generate'
    | '/api/admin/categories/$id'
    | '/api/admin/comments/$id'
    | '/api/admin/coupons/$id'
    | '/api/admin/media/$id'
    | '/api/admin/plans/$id'
    | '/api/admin/templates/$id'
    | '/api/admin/users/$id'
    | '/api/payments/razorpay/order'
    | '/api/payments/razorpay/verify'
    | '/api/payments/razorpay/webhook'
    | '/api/public/coupons/validate'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/affiliate-program'
    | '/blog'
    | '/careers'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/help-center'
    | '/how-it-works'
    | '/pricing'
    | '/privacy-policy'
    | '/templates'
    | '/terms-of-service'
    | '/account/login'
    | '/account/purchases'
    | '/account/register'
    | '/account/settings'
    | '/account/wishes'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/media'
    | '/admin/plans'
    | '/admin/templates'
    | '/admin/users'
    | '/wish/$id'
    | '/account/'
    | '/admin/'
    | '/admin/settings/system'
    | '/admin/settings/website'
    | '/api/account/purchases'
    | '/api/account/wishes'
    | '/api/admin/categories'
    | '/api/admin/comments'
    | '/api/admin/coupons'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/media'
    | '/api/admin/plans'
    | '/api/admin/stats'
    | '/api/admin/templates'
    | '/api/admin/users'
    | '/api/auth/me'
    | '/api/public/auth-me'
    | '/api/public/categories'
    | '/api/public/media'
    | '/api/public/plans'
    | '/api/public/settings'
    | '/api/public/templates'
    | '/api/public/wish'
    | '/api/wishes/cover'
    | '/api/wishes/generate'
    | '/api/admin/categories/$id'
    | '/api/admin/comments/$id'
    | '/api/admin/coupons/$id'
    | '/api/admin/media/$id'
    | '/api/admin/plans/$id'
    | '/api/admin/templates/$id'
    | '/api/admin/users/$id'
    | '/api/payments/razorpay/order'
    | '/api/payments/razorpay/verify'
    | '/api/payments/razorpay/webhook'
    | '/api/public/coupons/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateProgramRoute: typeof AffiliateProgramRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpCenterRoute: typeof HelpCenterRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WishIdRoute: typeof WishIdRoute
  ApiAccountPurchasesRoute: typeof ApiAccountPurchasesRoute
  ApiAccountWishesRoute: typeof ApiAccountWishesRoute
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRouteWithChildren
  ApiAdminCommentsRoute: typeof ApiAdminCommentsRouteWithChildren
  ApiAdminCouponsRoute: typeof ApiAdminCouponsRouteWithChildren
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminMediaRoute: typeof ApiAdminMediaRouteWithChildren
  ApiAdminPlansRoute: typeof ApiAdminPlansRouteWithChildren
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminTemplatesRoute: typeof ApiAdminTemplatesRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiPublicAuthMeRoute: typeof ApiPublicAuthMeRoute
  ApiPublicCategoriesRoute: typeof ApiPublicCategoriesRoute
  ApiPublicMediaRoute: typeof ApiPublicMediaRoute
  ApiPublicPlansRoute: typeof ApiPublicPlansRoute
  ApiPublicSettingsRoute: typeof ApiPublicSettingsRoute
  ApiPublicTemplatesRoute: typeof ApiPublicTemplatesRoute
  ApiPublicWishRoute: typeof ApiPublicWishRoute
  ApiWishesCoverRoute: typeof ApiWishesCoverRoute
  ApiWishesGenerateRoute: typeof ApiWishesGenerateRoute
  ApiPaymentsRazorpayOrderRoute: typeof ApiPaymentsRazorpayOrderRoute
  ApiPaymentsRazorpayVerifyRoute: typeof ApiPaymentsRazorpayVerifyRoute
  ApiPaymentsRazorpayWebhookRoute: typeof ApiPaymentsRazorpayWebhookRoute
  ApiPublicCouponsValidateRoute: typeof ApiPublicCouponsValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-program': {
      id: '/affiliate-program'
      path: '/affiliate-program'
      fullPath: '/affiliate-program'
      preLoaderRoute: typeof AffiliateProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/purchases': {
      id: '/account/purchases'
      path: '/purchases'
      fullPath: '/account/purchases'
      preLoaderRoute: typeof AccountPurchasesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/wishes': {
      id: '/account/wishes'
      path: '/wishes'
      fullPath: '/account/wishes'
      preLoaderRoute: typeof AccountWishesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/wish/$id': {
      id: '/wish/$id'
      path: '/wish/$id'
      fullPath: '/wish/$id'
      preLoaderRoute: typeof WishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/system': {
      id: '/admin/settings/system'
      path: '/settings/system'
      fullPath: '/admin/settings/system'
      preLoaderRoute: typeof AdminSettingsSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/website': {
      id: '/admin/settings/website'
      path: '/settings/website'
      fullPath: '/admin/settings/website'
      preLoaderRoute: typeof AdminSettingsWebsiteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/account/purchases': {
      id: '/api/account/purchases'
      path: '/api/account/purchases'
      fullPath: '/api/account/purchases'
      preLoaderRoute: typeof ApiAccountPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/wishes': {
      id: '/api/account/wishes'
      path: '/api/account/wishes'
      fullPath: '/api/account/wishes'
      preLoaderRoute: typeof ApiAccountWishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/comments': {
      id: '/api/admin/comments'
      path: '/api/admin/comments'
      fullPath: '/api/admin/comments'
      preLoaderRoute: typeof ApiAdminCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/coupons': {
      id: '/api/admin/coupons'
      path: '/api/admin/coupons'
      fullPath: '/api/admin/coupons'
      preLoaderRoute: typeof ApiAdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media': {
      id: '/api/admin/media'
      path: '/api/admin/media'
      fullPath: '/api/admin/media'
      preLoaderRoute: typeof ApiAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/plans': {
      id: '/api/admin/plans'
      path: '/api/admin/plans'
      fullPath: '/api/admin/plans'
      preLoaderRoute: typeof ApiAdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/templates': {
      id: '/api/admin/templates'
      path: '/api/admin/templates'
      fullPath: '/api/admin/templates'
      preLoaderRoute: typeof ApiAdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-me': {
      id: '/api/public/auth-me'
      path: '/api/public/auth-me'
      fullPath: '/api/public/auth-me'
      preLoaderRoute: typeof ApiPublicAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/categories': {
      id: '/api/public/categories'
      path: '/api/public/categories'
      fullPath: '/api/public/categories'
      preLoaderRoute: typeof ApiPublicCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media': {
      id: '/api/public/media'
      path: '/api/public/media'
      fullPath: '/api/public/media'
      preLoaderRoute: typeof ApiPublicMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plans': {
      id: '/api/public/plans'
      path: '/api/public/plans'
      fullPath: '/api/public/plans'
      preLoaderRoute: typeof ApiPublicPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/settings': {
      id: '/api/public/settings'
      path: '/api/public/settings'
      fullPath: '/api/public/settings'
      preLoaderRoute: typeof ApiPublicSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/templates': {
      id: '/api/public/templates'
      path: '/api/public/templates'
      fullPath: '/api/public/templates'
      preLoaderRoute: typeof ApiPublicTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wish': {
      id: '/api/public/wish'
      path: '/api/public/wish'
      fullPath: '/api/public/wish'
      preLoaderRoute: typeof ApiPublicWishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishes/cover': {
      id: '/api/wishes/cover'
      path: '/api/wishes/cover'
      fullPath: '/api/wishes/cover'
      preLoaderRoute: typeof ApiWishesCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishes/generate': {
      id: '/api/wishes/generate'
      path: '/api/wishes/generate'
      fullPath: '/api/wishes/generate'
      preLoaderRoute: typeof ApiWishesGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories/$id': {
      id: '/api/admin/categories/$id'
      path: '/$id'
      fullPath: '/api/admin/categories/$id'
      preLoaderRoute: typeof ApiAdminCategoriesIdRouteImport
      parentRoute: typeof ApiAdminCategoriesRoute
    }
    '/api/admin/comments/$id': {
      id: '/api/admin/comments/$id'
      path: '/$id'
      fullPath: '/api/admin/comments/$id'
      preLoaderRoute: typeof ApiAdminCommentsIdRouteImport
      parentRoute: typeof ApiAdminCommentsRoute
    }
    '/api/admin/coupons/$id': {
      id: '/api/admin/coupons/$id'
      path: '/$id'
      fullPath: '/api/admin/coupons/$id'
      preLoaderRoute: typeof ApiAdminCouponsIdRouteImport
      parentRoute: typeof ApiAdminCouponsRoute
    }
    '/api/admin/media/$id': {
      id: '/api/admin/media/$id'
      path: '/$id'
      fullPath: '/api/admin/media/$id'
      preLoaderRoute: typeof ApiAdminMediaIdRouteImport
      parentRoute: typeof ApiAdminMediaRoute
    }
    '/api/admin/plans/$id': {
      id: '/api/admin/plans/$id'
      path: '/$id'
      fullPath: '/api/admin/plans/$id'
      preLoaderRoute: typeof ApiAdminPlansIdRouteImport
      parentRoute: typeof ApiAdminPlansRoute
    }
    '/api/admin/templates/$id': {
      id: '/api/admin/templates/$id'
      path: '/$id'
      fullPath: '/api/admin/templates/$id'
      preLoaderRoute: typeof ApiAdminTemplatesIdRouteImport
      parentRoute: typeof ApiAdminTemplatesRoute
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/payments/razorpay/order': {
      id: '/api/payments/razorpay/order'
      path: '/api/payments/razorpay/order'
      fullPath: '/api/payments/razorpay/order'
      preLoaderRoute: typeof ApiPaymentsRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/razorpay/verify': {
      id: '/api/payments/razorpay/verify'
      path: '/api/payments/razorpay/verify'
      fullPath: '/api/payments/razorpay/verify'
      preLoaderRoute: typeof ApiPaymentsRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/razorpay/webhook': {
      id: '/api/payments/razorpay/webhook'
      path: '/api/payments/razorpay/webhook'
      fullPath: '/api/payments/razorpay/webhook'
      preLoaderRoute: typeof ApiPaymentsRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/coupons/validate': {
      id: '/api/public/coupons/validate'
      path: '/api/public/coupons/validate'
      fullPath: '/api/public/coupons/validate'
      preLoaderRoute: typeof ApiPublicCouponsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountLoginRoute: typeof AccountLoginRoute
  AccountPurchasesRoute: typeof AccountPurchasesRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishesRoute: typeof AccountWishesRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountLoginRoute: AccountLoginRoute,
  AccountPurchasesRoute: AccountPurchasesRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishesRoute: AccountWishesRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSettingsSystemRoute: typeof AdminSettingsSystemRoute
  AdminSettingsWebsiteRoute: typeof AdminSettingsWebsiteRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSettingsSystemRoute: AdminSettingsSystemRoute,
  AdminSettingsWebsiteRoute: AdminSettingsWebsiteRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiAdminCategoriesRouteChildren {
  ApiAdminCategoriesIdRoute: typeof ApiAdminCategoriesIdRoute
}

const ApiAdminCategoriesRouteChildren: ApiAdminCategoriesRouteChildren = {
  ApiAdminCategoriesIdRoute: ApiAdminCategoriesIdRoute,
}

const ApiAdminCategoriesRouteWithChildren =
  ApiAdminCategoriesRoute._addFileChildren(ApiAdminCategoriesRouteChildren)

interface ApiAdminCommentsRouteChildren {
  ApiAdminCommentsIdRoute: typeof ApiAdminCommentsIdRoute
}

const ApiAdminCommentsRouteChildren: ApiAdminCommentsRouteChildren = {
  ApiAdminCommentsIdRoute: ApiAdminCommentsIdRoute,
}

const ApiAdminCommentsRouteWithChildren =
  ApiAdminCommentsRoute._addFileChildren(ApiAdminCommentsRouteChildren)

interface ApiAdminCouponsRouteChildren {
  ApiAdminCouponsIdRoute: typeof ApiAdminCouponsIdRoute
}

const ApiAdminCouponsRouteChildren: ApiAdminCouponsRouteChildren = {
  ApiAdminCouponsIdRoute: ApiAdminCouponsIdRoute,
}

const ApiAdminCouponsRouteWithChildren = ApiAdminCouponsRoute._addFileChildren(
  ApiAdminCouponsRouteChildren,
)

interface ApiAdminMediaRouteChildren {
  ApiAdminMediaIdRoute: typeof ApiAdminMediaIdRoute
}

const ApiAdminMediaRouteChildren: ApiAdminMediaRouteChildren = {
  ApiAdminMediaIdRoute: ApiAdminMediaIdRoute,
}

const ApiAdminMediaRouteWithChildren = ApiAdminMediaRoute._addFileChildren(
  ApiAdminMediaRouteChildren,
)

interface ApiAdminPlansRouteChildren {
  ApiAdminPlansIdRoute: typeof ApiAdminPlansIdRoute
}

const ApiAdminPlansRouteChildren: ApiAdminPlansRouteChildren = {
  ApiAdminPlansIdRoute: ApiAdminPlansIdRoute,
}

const ApiAdminPlansRouteWithChildren = ApiAdminPlansRoute._addFileChildren(
  ApiAdminPlansRouteChildren,
)

interface ApiAdminTemplatesRouteChildren {
  ApiAdminTemplatesIdRoute: typeof ApiAdminTemplatesIdRoute
}

const ApiAdminTemplatesRouteChildren: ApiAdminTemplatesRouteChildren = {
  ApiAdminTemplatesIdRoute: ApiAdminTemplatesIdRoute,
}

const ApiAdminTemplatesRouteWithChildren =
  ApiAdminTemplatesRoute._addFileChildren(ApiAdminTemplatesRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateProgramRoute: AffiliateProgramRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpCenterRoute: HelpCenterRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TemplatesRoute: TemplatesRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WishIdRoute: WishIdRoute,
  ApiAccountPurchasesRoute: ApiAccountPurchasesRoute,
  ApiAccountWishesRoute: ApiAccountWishesRoute,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRouteWithChildren,
  ApiAdminCommentsRoute: ApiAdminCommentsRouteWithChildren,
  ApiAdminCouponsRoute: ApiAdminCouponsRouteWithChildren,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminMediaRoute: ApiAdminMediaRouteWithChildren,
  ApiAdminPlansRoute: ApiAdminPlansRouteWithChildren,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminTemplatesRoute: ApiAdminTemplatesRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiPublicAuthMeRoute: ApiPublicAuthMeRoute,
  ApiPublicCategoriesRoute: ApiPublicCategoriesRoute,
  ApiPublicMediaRoute: ApiPublicMediaRoute,
  ApiPublicPlansRoute: ApiPublicPlansRoute,
  ApiPublicSettingsRoute: ApiPublicSettingsRoute,
  ApiPublicTemplatesRoute: ApiPublicTemplatesRoute,
  ApiPublicWishRoute: ApiPublicWishRoute,
  ApiWishesCoverRoute: ApiWishesCoverRoute,
  ApiWishesGenerateRoute: ApiWishesGenerateRoute,
  ApiPaymentsRazorpayOrderRoute: ApiPaymentsRazorpayOrderRoute,
  ApiPaymentsRazorpayVerifyRoute: ApiPaymentsRazorpayVerifyRoute,
  ApiPaymentsRazorpayWebhookRoute: ApiPaymentsRazorpayWebhookRoute,
  ApiPublicCouponsValidateRoute: ApiPublicCouponsValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
